export const endpoints = {
  auth: {
    login: '/accounts/login/',
    register: '/accounts/register/',
    profile: '/accounts/profile/',
    refresh: '/accounts/refresh/',
    logout: '/accounts/logout/',
    dashboards: '/accounts/dashboards/',
    changePassword: '/accounts/change-password/',
  },
  doctors: '/doctors/doctors/',
  doctorSchedules: '/doctors/doctor-schedules/',
  patients: '/patients/patients/',
  appointments: '/appointments/appointments/',
  medicalRecords: '/medical_record/medical-records/',
  prescriptions: '/medical_record/prescriptions/',
  medicines: '/pharmacy/medicines/',
  pharmacyOrders: '/pharmacy/pharmacy-order/',
  pharmacyOrderItems: '/pharmacy/order-item/',
  labTests: '/laboratory/tests/',
  labOrders: '/laboratory/orders/',
  labReports: '/laboratory/reports/',
  bills: '/billing/bills/',
  chatbot: {
    ask: '/chatbot/ask/',
    status: '/chatbot/status/',
  },
  reports: {
    dashboard: '/reports/dashboard/',
    revenue: '/reports/revenue/',
    appointments: '/reports/appointments/',
    lab: '/reports/lab/',
    pharmacy: '/reports/pharmacy/',
  },
}
