import { endpoints } from '../api/endpoints'

export const resourceConfigs = {
  doctors: {
    permissions: {
      create: ['admin', 'receptionist', 'doctor'],
      edit: ['admin', 'receptionist'],
      delete: ['admin', 'receptionist'],
    },
    title: 'Doctors',
    description: 'Manage doctor profiles and availability.',
    endpoint: endpoints.doctors,
    searchPlaceholder: 'Search by username or specialization',
    orderingOptions: [
      { value: 'experience', label: 'Experience Asc' },
      { value: '-experience', label: 'Experience Desc' },
      { value: 'consultation_fee', label: 'Fee Asc' },
      { value: '-consultation_fee', label: 'Fee Desc' },
    ],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'username', label: 'Username' },
      { key: 'specialization', label: 'Specialization' },
      { key: 'experience', label: 'Experience' },
      { key: 'consultation_fee', label: 'Fee' },
      { key: 'availability', label: 'Availability' },
    ],
    formFields: [
      { name: 'user', label: 'User ID', type: 'number', required: true, min: 1 },
      { name: 'specialization', label: 'Specialization', required: true, minLength: 2 },
      { name: 'experience', label: 'Experience' },
      { name: 'qualification', label: 'Qualification' },
      { name: 'consultation_fee', label: 'Consultation Fee', type: 'number', min: 0 },
      { name: 'room_no', label: 'Room Number' },
      { name: 'bio', label: 'Bio', type: 'textarea' },
      {
        name: 'availability',
        label: 'Availability',
        type: 'select',
        options: [
          { value: 'true', label: 'Available' },
          { value: 'false', label: 'Unavailable' },
        ],
      },
    ],
    payloadBuilder: (values) => ({
      ...values,
      availability: String(values.availability) === 'true',
    }),
  },
  doctorSchedules: {
    permissions: {
      create: ['admin', 'receptionist', 'doctor'],
      edit: ['admin', 'receptionist', 'doctor'],
      delete: ['admin', 'receptionist', 'doctor'],
    },
    title: 'Doctor Schedules',
    description: 'Configure weekly doctor availability slots.',
    endpoint: endpoints.doctorSchedules,
    searchPlaceholder: 'Search by doctor or day',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'doctor', label: 'Doctor' },
      { key: 'day', label: 'Day' },
      { key: 'start_time', label: 'Start' },
      { key: 'end_time', label: 'End' },
      { key: 'max_patients', label: 'Max Patients' },
      { key: 'is_booked', label: 'Booked' },
    ],
    lookups: [{ key: 'doctors', endpoint: endpoints.doctors, labelBuilder: (row) => row.username || `Doctor ${row.id}` }],
    formFields: [
      { name: 'doctor', label: 'Doctor', type: 'select', lookupKey: 'doctors', required: true },
      { name: 'day', label: 'Day', required: true },
      { name: 'start_time', label: 'Start Time', type: 'time' },
      { name: 'end_time', label: 'End Time', type: 'time' },
      { name: 'max_patients', label: 'Max Patients', type: 'number', required: true, min: 1 },
      {
        name: 'is_booked',
        label: 'Booked',
        type: 'select',
        options: [
          { value: 'false', label: 'No' },
          { value: 'true', label: 'Yes' },
        ],
      },
    ],
    payloadBuilder: (values) => ({ ...values, doctor: Number(values.doctor), max_patients: Number(values.max_patients), is_booked: String(values.is_booked) === 'true' }),
  },
  patients: {
    permissions: {
      create: ['admin', 'receptionist', 'patient'],
      edit: ['admin', 'receptionist'],
      delete: ['admin', 'receptionist'],
    },
    title: 'Patients',
    description: 'Create and track patient profiles.',
    endpoint: endpoints.patients,
    searchPlaceholder: 'Search patients by username or phone',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'user', label: 'User' },
      { key: 'age', label: 'Age' },
      { key: 'phone', label: 'Phone' },
      { key: 'address', label: 'Address' },
    ],
    formFields: [
      { name: 'user', label: 'User ID', type: 'number', required: true, min: 1 },
      { name: 'age', label: 'Age', type: 'number', min: 0 },
      { name: 'phone', label: 'Phone' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'medical_history', label: 'Medical History', type: 'textarea' },
    ],
  },
  appointments: {
    permissions: {
      create: ['admin', 'receptionist', 'patient'],
      edit: ['admin', 'receptionist', 'doctor', 'patient'],
      delete: ['admin', 'receptionist', 'doctor', 'patient'],
    },
    title: 'Appointments',
    description: 'Book and manage appointment lifecycle.',
    endpoint: endpoints.appointments,
    searchPlaceholder: 'Search by patient/doctor/reason',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'patient', label: 'Patient' },
      { key: 'doctor', label: 'Doctor' },
      { key: 'appointment_date', label: 'Date' },
      { key: 'appointment_time', label: 'Time' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    lookups: [
      { key: 'doctors', endpoint: endpoints.doctors, labelBuilder: (row) => row.username || `Doctor ${row.id}` },
      { key: 'patients', endpoint: endpoints.patients, labelBuilder: (row) => `Patient ${row.id}` },
      { key: 'doctorSchedules', endpoint: endpoints.doctorSchedules, labelBuilder: (row) => `${row.doctor_name || row.doctor} - ${row.day}` },
    ],
    formFields: [
      { name: 'patient', label: 'Patient', type: 'select', lookupKey: 'patients', required: true },
      { name: 'doctor', label: 'Doctor', type: 'select', lookupKey: 'doctors', required: true },
      { name: 'doctor_schedules', label: 'Schedule', type: 'select', lookupKey: 'doctorSchedules', required: true },
      { name: 'appointment_date', label: 'Appointment Date', type: 'date', required: true },
      { name: 'appointment_time', label: 'Appointment Time', type: 'time', required: true },
      { name: 'reason', label: 'Reason', type: 'textarea' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'pending', label: 'Pending' },
          { value: 'confirmed', label: 'Confirmed' },
          { value: 'completed', label: 'Completed' },
        ],
      },
    ],
    payloadBuilder: (values) => ({ ...values, patient: Number(values.patient), doctor: Number(values.doctor), doctor_schedules: Number(values.doctor_schedules) }),
  },
  medicines: {
    permissions: {
      create: ['admin', 'receptionist', 'pharmacist'],
      edit: ['admin', 'receptionist', 'pharmacist'],
      delete: ['admin', 'receptionist', 'pharmacist'],
    },
    title: 'Medicine Inventory',
    description: 'Track stock, pricing and expiry of medicines.',
    endpoint: endpoints.medicines,
    searchPlaceholder: 'Search medicines by name/category',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'price', label: 'Price' },
      { key: 'stock_quantity', label: 'Stock' },
      { key: 'expiry_date', label: 'Expiry Date' },
    ],
    formFields: [
      { name: 'name', label: 'Medicine Name', required: true, minLength: 2 },
      { name: 'category', label: 'Category', required: true },
      { name: 'price', label: 'Price', type: 'number', required: true, min: 0 },
      { name: 'stock_quantity', label: 'Stock Quantity', type: 'number', required: true, min: 0 },
      { name: 'expiry_date', label: 'Expiry Date', type: 'date', required: true },
    ],
  },
  pharmacyOrderItems: {
    permissions: {
      create: ['admin', 'receptionist', 'pharmacist'],
      edit: ['admin', 'receptionist', 'pharmacist'],
      delete: ['pharmacist'],
    },
    title: 'Pharmacy Order Items',
    description: 'View and manage pharmacy order line items.',
    endpoint: endpoints.pharmacyOrderItems,
    searchPlaceholder: 'Search order items',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'order', label: 'Order' },
      { key: 'medicine', label: 'Medicine' },
      { key: 'quantity', label: 'Quantity' },
      { key: 'price', label: 'Price' },
      { key: 'total_price', label: 'Total Price' },
    ],
    lookups: [
      { key: 'pharmacyOrders', endpoint: endpoints.pharmacyOrders, labelBuilder: (row) => `Order ${row.id}` },
      { key: 'medicines', endpoint: endpoints.medicines, labelBuilder: (row) => row.name },
    ],
    formFields: [
      { name: 'order', label: 'Order', type: 'select', lookupKey: 'pharmacyOrders' },
      { name: 'medicine', label: 'Medicine', type: 'select', lookupKey: 'medicines' },
      { name: 'quantity', label: 'Quantity', type: 'number' },
    ],
    payloadBuilder: (values) => ({ order: Number(values.order), medicine: Number(values.medicine), quantity: Number(values.quantity) }),
  },
  labTests: {
    permissions: {
      create: ['admin', 'receptionist', 'lab_technician'],
      edit: ['admin', 'receptionist', 'lab_technician'],
      delete: ['admin', 'receptionist', 'lab_technician'],
    },
    title: 'Laboratory Tests',
    description: 'Manage lab test catalog.',
    endpoint: endpoints.labTests,
    searchPlaceholder: 'Search tests by name or description',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Test' },
      { key: 'description', label: 'Description' },
      { key: 'price', label: 'Price' },
    ],
    formFields: [
      { name: 'name', label: 'Test Name', required: true, minLength: 2 },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'price', label: 'Price', type: 'number', required: true, min: 0 },
    ],
  },
  labOrders: {
    permissions: {
      create: ['admin', 'receptionist', 'doctor'],
      edit: ['admin', 'receptionist', 'doctor'],
      delete: ['admin', 'receptionist', 'doctor'],
    },
    title: 'Laboratory Orders',
    description: 'Create and monitor lab test orders.',
    endpoint: endpoints.labOrders,
    searchPlaceholder: 'Search lab orders',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'patient', label: 'Patient' },
      { key: 'doctor', label: 'Doctor' },
      { key: 'medical_record', label: 'Medical Record' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    lookups: [
      { key: 'patients', endpoint: endpoints.patients, labelBuilder: (row) => `Patient ${row.id}` },
      { key: 'doctors', endpoint: endpoints.doctors, labelBuilder: (row) => row.username || `Doctor ${row.id}` },
      { key: 'medicalRecords', endpoint: endpoints.medicalRecords, labelBuilder: (row) => `Record ${row.id}` },
      { key: 'labTests', endpoint: endpoints.labTests, labelBuilder: (row) => row.name },
    ],
    formFields: [
      { name: 'patient', label: 'Patient', type: 'select', lookupKey: 'patients', required: true },
      { name: 'doctor', label: 'Doctor', type: 'select', lookupKey: 'doctors', required: true },
      { name: 'medical_record', label: 'Medical Record', type: 'select', lookupKey: 'medicalRecords', required: true },
      { name: 'tests', label: 'Lab Tests', type: 'multiselect', lookupKey: 'labTests', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'pending', label: 'Pending' },
          { value: 'completed', label: 'Completed' },
        ],
      },
    ],
    payloadBuilder: (values) => ({
      ...values,
      patient: Number(values.patient),
      doctor: Number(values.doctor),
      medical_record: Number(values.medical_record),
      tests: (values.tests || []).map(Number),
    }),
  },
  bills: {
    permissions: {
      create: ['admin', 'receptionist'],
      edit: ['admin', 'receptionist'],
      delete: ['admin', 'receptionist'],
    },
    title: 'Billing',
    description: 'Generate and manage bills.',
    endpoint: endpoints.bills,
    searchPlaceholder: 'Search bills',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'patient', label: 'Patient' },
      { key: 'doctor', label: 'Doctor' },
      { key: 'total_amount', label: 'Total' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'created_at', label: 'Created At' },
    ],
    lookups: [
      { key: 'appointments', endpoint: endpoints.appointments, labelBuilder: (row) => `Appointment ${row.id}` },
      { key: 'pharmacyOrders', endpoint: endpoints.pharmacyOrders, labelBuilder: (row) => `Order ${row.id}` },
      { key: 'labOrders', endpoint: endpoints.labOrders, labelBuilder: (row) => `Lab Order ${row.id}` },
    ],
    formFields: [
      { name: 'appointment', label: 'Appointment', type: 'select', lookupKey: 'appointments', required: true },
      { name: 'pharmacy_order', label: 'Pharmacy Order', type: 'select', lookupKey: 'pharmacyOrders' },
      { name: 'lab_order', label: 'Lab Order', type: 'select', lookupKey: 'labOrders' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'pending', label: 'Pending' },
          { value: 'paid', label: 'Paid' },
        ],
      },
    ],
    payloadBuilder: (values) => ({
      appointment: Number(values.appointment),
      pharmacy_order: values.pharmacy_order ? Number(values.pharmacy_order) : null,
      lab_order: values.lab_order ? Number(values.lab_order) : null,
      status: values.status,
    }),
  },
}
